# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.DateTimeField(blank=True, null=True)),
                ('Age', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, max_length=100, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.TextField(blank=True, max_length=900, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('Blood_Group', models.CharField(blank=True, max_length=100, null=True)),
                ('Email_Id', models.CharField(blank=True, max_length=100, null=True)),
                ('Diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('Chief_Complains', models.TextField(blank=True, max_length=900, null=True)),
                ('Past_History', models.CharField(blank=True, max_length=100, null=True)),
                ('DRUG_Allergy', models.CharField(blank=True, max_length=100, null=True)),
                ('Treatment', models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Oint', 'Oint'), ('Syrup', 'Syrup'), ('Gel', 'Gel'), ('Cream', 'Cream'), ('Injection', 'Injection')], max_length=100, null=True)),
                ('Investigation', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientFollowUpCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complain', models.DateTimeField(blank=True, null=True)),
                ('Treatment', models.CharField(blank=True, max_length=100, null=True)),
                ('Diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(auto_now=True, null=True)),
                ('Patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Patient')),
            ],
        ),
    ]
