# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20180317_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
