# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20180317_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Treatment_Desciption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
