# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20180317_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientfollowupcase',
            name='Treatment_Desciption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Treatment',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Oint', 'Oint'), ('Syrup', 'Syrup'), ('Gel', 'Gel'), ('Cream', 'Cream'), ('Soap', 'Soap'), ('Injection', 'Injection')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientfollowupcase',
            name='Treatment',
            field=models.CharField(blank=True, choices=[('Tablet', 'Tablet'), ('Oint', 'Oint'), ('Syrup', 'Syrup'), ('Gel', 'Gel'), ('Cream', 'Cream'), ('Soap', 'Soap'), ('Injection', 'Injection')], max_length=100, null=True),
        ),
    ]
