# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_auto_20180317_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Reference_Doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientfollowupcase',
            name='Reference_Doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
