# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0010_auto_20180317_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfollowupcase',
            name='Complain',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
