# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0011_auto_20180317_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainComplain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Chief_Complains',
        ),
        migrations.AlterField(
            model_name='patientfollowupcase',
            name='Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Chief_Complains',
            field=models.ManyToManyField(blank=True, to='Patient.MainComplain'),
        ),
    ]
